ministryofjustice/dps-monitor

jobs/circle_ci.rb
widgets/circle_ci/circle_ci.html

It will go through to the workflow if you click the on the avatar, or the specific build if no workflow exists.

Adding the ability to click through to circle ci on each build widget.

---

README.md
dashboards/circle.erb
jobs/circle_ci.rb
jobs/health.rb

When production environment is available it will be added to overview & prod server sections.

Added circleCI and health/info for Community proxy (stage only)

---

README.md
dashboards/circle.erb
jobs/circle_ci.rb
jobs/health.rb

Reverts ministryofjustice/notm-monitor#8

Revert "Added circleCI and health/info for Community proxy (stage only)"

---

Gemfile.lock
README.md
dashboards/circle.erb
dashboards/health.erb
dashboards/overview.erb
jobs/circle_ci.rb
jobs/health.rb

Adds community proxy health and build info

Community proxy health

---

jobs/health.rb

Only one currently is the community-proxy, but this change allows for a configurable list of them.
Only ignores for stage at present, but the same check could be added to the production health checks.

Ignore out-of-date check for a given list of services with no dev instances.

---

dashboards/circle.erb
dashboards/health.erb
jobs/circle_ci.rb
jobs/health.rb

Also adds circle job monitoring.

Added sentence-planning (dev) service to health/info endpoints

---

jobs/health.rb

Reverts ministryofjustice/notm-monitor#44

Revert "DT-313: updated Prod keyworker-api url"

---

dashboards/circle.erb
dashboards/health.erb
dashboards/overview.erb
dashboards/pathfinder-overview.erb
jobs/circle_ci.rb
jobs/health.rb

* Added offender-search to the health and circle jobs.
* Added offender-search and Pathfinder services to the overview dashboard.
* Added offender-search to the health & circle dashboards
* Added community-api and offender search to the pathfinder-overview dashboard.
Changes to the offender-search service were made so that it responds as expected by the monitor, and these are now in prod - and a local instance of the monitor now shows these as green.

PAT-552: Add offender-search to jobs and dashboards.

---

helm_deploy/dps-monitor/templates/deployment.yaml
helm_deploy/dps-monitor/templates/ingress.yaml

Reverts ministryofjustice/dps-monitor#91

Revert "DT-917: Switch out deprecated APIs"

---

helm_deploy/dps-monitor/templates/deployment.yaml
helm_deploy/dps-monitor/templates/ingress.yaml

Reverts ministryofjustice/dps-monitor#92

Revert "Revert "DT-917: Switch out deprecated APIs""

---

dashboards/circle.erb
dashboards/overview.erb
jobs/circle_ci.rb

updated following to use main branch:
- offender-risk-profiler 
- categorisation-tool
- pathfinder
- pathfinder-api

PAT-931 update main branch offender-risk-profiler, categorisation-tool, pathfinder and pathfinder-api

---

dashboards/circle.erb
dashboards/health.erb
dashboards/overview.erb
dashboards/pathfinder-overview.erb
jobs/circle_ci.rb
jobs/health.rb

- Add the SOCU (manage-soc-service) service to the dashboards

PAT-949: add SOCU service

---

dashboards/pathfinder-overview.erb
jobs/health.rb

- fix no version information for socu
- fix pathfinder and pathfinder-api not showing circle jobs on pathfinder-overview dashboard

Pat 949 fix no version information for socu

---

dashboards/circle.erb
dashboards/health.erb
dashboards/overview.erb
jobs/circle_ci.rb
jobs/health.rb

Reverts ministryofjustice/dps-monitor#122

Revert "NN-2951: Add feedback and support service"

---

dashboards/circle.erb
dashboards/health.erb
dashboards/overview.erb
jobs/circle_ci.rb
jobs/health.rb

New health endpoint is now live and can be used here.

Nn 2951 support service monitoring

---

Gemfile.lock
README.md
dashboards/health.erb
jobs/health.rb

DT-1156 Add staging environments to monitor

---

jobs/health.rb

Alters domain from .hmpps.service -> .prison.service

AR-723: Update domain for manage-intelligence services

---

Gemfile
Gemfile.lock

https://dsdmoj.atlassian.net/browse/DT-2908

DT-2908: specify version of date package to fix CVE

---

jobs/projects.rb

- [projects.rb](https://github.com/ministryofjustice/dps-monitor/blob/a68c5b426539151311ab8515eeccf9b48210f8e0/jobs/projects.rb#L555)

Add SED team to health

---

jobs/projects.rb

Update VSiP Urls for failing monitor endpoints.

VB-1032: Update VSiP urls

---

jobs/projects.rb

Adding new dev services activities management frontend and and backend.

SAA-16 add activities management ui and api.

---

.circleci/config.yml
helm_deploy/dps-monitor/Chart.yaml
helm_deploy/values-prod.yaml

https://dsdmoj.atlassian.net/browse/HEAT-15

HEAT-15: use latest Kubernetes Ingress Controller - dual ingress; bump HMPPS Orb

---

helm_deploy/values-prod.yaml

https://dsdmoj.atlassian.net/browse/HEAT-15

HEAT-15: disable old ingress v0_47

---

jobs/projects.rb

SDI-396 Change domain name and namespace
